AllCops:
  Include:
    - 'app/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'app/models/ahoy/*.rb'
    - 'bin/**/*.rb'

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false