language: ruby

before_install:
  - nvm install 10.13.0

env:
  global:
    - NODE_ENV=test
    - RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

services:
  - postgresql

before_script:
  - bundle exec rake db:setup
  - yarn

addons:
  chrome: stable

script:
  - bundle exec rake test
  - bundle exec rails webpacker:compile
  - bundle exec rake test:system