language: ruby

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database fusebox_insights_test;' -U postgres

addons:
  sources:
    - google-chrome
  apt:
    packages:
      - google-chrome-stable

script:
  - bundle exec rake test:system